from app.prompt.system_prompts import (
    CHAT_SYSTEM_PROMPT,
    CHESS_OPPONENT_SYSTEM_PROMPT,
    CHESS_SYSTEM_PROMPT,
    MINESWEEPER_SYSTEM_PROMPT,
)

__all__ = [
    "CHAT_SYSTEM_PROMPT",
    "MINESWEEPER_SYSTEM_PROMPT",
    "CHESS_SYSTEM_PROMPT",
    "CHESS_OPPONENT_SYSTEM_PROMPT",
]
