from app.prompt.system_prompts import (
    CHAT_DAILY_PROMPT,
    CHAT_GAME_DATA_QUERY_PROMPT,
    CHAT_INTENT_RECOGNITION_PROMPT,
    CHAT_SYSTEM_PROMPT,
    CHESS_OPPONENT_SYSTEM_PROMPT,
    CHESS_SYSTEM_PROMPT,
    MINESWEEPER_SYSTEM_PROMPT,
)

__all__ = [
    "CHAT_SYSTEM_PROMPT",
    "CHAT_INTENT_RECOGNITION_PROMPT",
    "CHAT_DAILY_PROMPT",
    "CHAT_GAME_DATA_QUERY_PROMPT",
    "MINESWEEPER_SYSTEM_PROMPT",
    "CHESS_SYSTEM_PROMPT",
    "CHESS_OPPONENT_SYSTEM_PROMPT",
]
