CREATE TABLE IF NOT EXISTS players (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    account TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    gold INTEGER NOT NULL DEFAULT 0,
    level INTEGER NOT NULL DEFAULT 1
);
